apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
  - ../../base
images:
  - name: civicpulse-backend
    newName: ghcr.io/abdullah-netiz/civicpulse-backend
    newTag: IMAGE_TAG
  - name: civicpulse-frontend
    newName: ghcr.io/abdullah-netiz/civicpulse-frontend
    newTag: IMAGE_TAG
patches:
  - path: config.patch.yaml
