from typing import Protocol


class CacheProvider(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, expire_seconds: int = 30) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def increment_rate_limit(self, key: str, window_seconds: int) -> int: ...
